export { HELP_TEXT, UsageError, parseCommandLine } from './args.js';
export type { DaemonCommand, DaemonOptions, InstallScope, PairingMode, ParsedCommandLine } from './args.js';
export { SYSTEMD_MARKER, UnsupportedHostError, assertSupportedHost, hostArchitecture, readHostFacts } from './platform.js';
export type { HostFacts } from './platform.js';
export { runInstall } from './commands/install.js';
export { runStart, runStatus, runStop } from './commands/lifecycle.js';
export { runApprovals, runPairing, runResolveApproval } from './commands/pairing.js';
export { runResetIdentity, runUninstall } from './commands/uninstall.js';
export { runUpgrade } from './commands/upgrade.js';
export { NotInstalledError, resolveContext } from './context.js';
export { installLayout, readInstallRecord, writeInstallRecord } from './layout.js';
export { preflightToolchain, buildFromSource } from './source.js';
