import { open, readFile, readlink, readdir, realpath, stat } from "node:fs/promises";
import { homedir } from "node:os";
import { isAbsolute, join, relative, resolve } from "node:path";

export interface TargetAgentRequest {protocol:1;provider:"codex";sessionId:string;proof:string;cursor:number;maxRecords:32;maxBytes:262144}
export interface TargetHelperOptions {procRoot?:string;home?:string}

/** Linux target-side process/writer proof. Only a rollout held writable by a
 * proof-bearing process may be read; timestamps choose only between already
 * proven root rollouts and are never identity evidence. */
export async function readProvenCodexJournal(request:TargetAgentRequest,options:TargetHelperOptions={}):Promise<Record<string,unknown>>{
  validate(request);const procRoot=resolve(options.procRoot??"/proc");const sessions=resolve(options.home??homedir(),".codex","sessions");
  const pids=await proofBearingProcesses(procRoot,request.proof);const candidates: {path:string;mtimeMs:number}[]=[];
  for(const pid of pids)for(const path of await writableFiles(procRoot,pid))try{const canonical=await realpath(path);const root=await realpath(sessions);const rel=relative(root,canonical);if(!rel||rel.startsWith("..")||isAbsolute(rel)||!canonical.endsWith(".jsonl"))continue;const first=await firstRecord(canonical);if(isRootSession(first))candidates.push({path:canonical,mtimeMs:(await stat(canonical)).mtimeMs});}catch{/* raced or unsafe */}
  candidates.sort((a,b)=>b.mtimeMs-a.mtimeMs||a.path.localeCompare(b.path));const selected=candidates[0];if(!selected)return{protocol:1,provider:"codex",sessionId:request.sessionId,proof:request.proof,cursor:request.cursor,records:[],state:"unavailable"};
  const result=await readBatch(selected.path,request.cursor,request.maxRecords,request.maxBytes);return{protocol:1,provider:"codex",sessionId:request.sessionId,proof:request.proof,...result};
}
async function proofBearingProcesses(procRoot:string,proof:string):Promise<string[]>{const entries=await readdir(procRoot,{withFileTypes:true});const found:string[]=[];for(const entry of entries){if(!entry.isDirectory()||!/^\d+$/u.test(entry.name))continue;try{const env=await readFile(join(procRoot,entry.name,"environ"));if(env.includes(Buffer.from(`TERMINAY_SESSION_PROOF=${proof}\0`)))found.push(entry.name);}catch{/* inaccessible */}}return found;}
async function writableFiles(procRoot:string,pid:string):Promise<string[]>{const fdRoot=join(procRoot,pid,"fd");const entries=await readdir(fdRoot,{withFileTypes:true}).catch(()=>[]);const paths:string[]=[];for(const entry of entries){if(!/^\d+$/u.test(entry.name))continue;try{const flags=Number.parseInt((await readFile(join(procRoot,pid,"fdinfo",entry.name),"utf8")).match(/^flags:\s*([0-7]+)/mu)?.[1]??"0",8);if((flags&3)===0)continue;const path=await readlink(join(fdRoot,entry.name));if(isAbsolute(path))paths.push(path.replace(/ \(deleted\)$/u,""));}catch{/* raced */}}return paths;}
async function firstRecord(path:string):Promise<unknown>{const handle=await open(path,"r");try{const buffer=Buffer.alloc(65536);const {bytesRead}=await handle.read(buffer,0,buffer.length,0);const line=buffer.subarray(0,bytesRead).toString("utf8").split("\n",1)[0];return JSON.parse(line??"");}finally{await handle.close();}}
function isRootSession(value:unknown):boolean{if(!value||typeof value!=="object"||Array.isArray(value))return false;const record=value as Record<string,unknown>;if(record.type!=="session_meta"||!record.payload||typeof record.payload!=="object"||Array.isArray(record.payload))return false;const source=(record.payload as Record<string,unknown>).source;return !(source&&typeof source==="object"&&!Array.isArray(source)&&"subagent" in source);}
async function readBatch(path:string,cursor:number,maxRecords:number,maxBytes:number):Promise<{cursor:number;records:unknown[]}>{const metadata=await stat(path);if(cursor>metadata.size)cursor=0;const length=Math.min(metadata.size-cursor,maxBytes);const handle=await open(path,"r");try{const buffer=Buffer.alloc(length);const {bytesRead}=await handle.read(buffer,0,length,cursor);const text=buffer.subarray(0,bytesRead).toString("utf8");const complete=text.lastIndexOf("\n");if(complete<0)return{cursor,records:[]};const records:unknown[]=[];let consumed=0;for(const line of text.slice(0,complete+1).split("\n")){if(!line)continue;consumed+=Buffer.byteLength(line)+1;if(records.length>=maxRecords)break;try{const value=JSON.parse(line);if(value&&typeof value==="object"&&!Array.isArray(value))records.push(value);}catch{/* malformed bounded record */}}return{cursor:cursor+consumed,records};}finally{await handle.close();}}
function validate(value:TargetAgentRequest):void{if(value.protocol!==1||value.provider!=="codex"||!Number.isSafeInteger(value.cursor)||value.cursor<0||value.maxRecords!==32||value.maxBytes!==262144||!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/u.test(value.sessionId)||!/^[A-Za-z0-9_-]{32,128}$/u.test(value.proof))throw new TypeError("invalid target helper request");}
