import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { JsonValue, ProvisioningResult } from "@terminay/extension-api";
import type { ExtensionHostManager } from "./manager.js";
import { SSH_PROVIDER_ID, type ComposedSshRuntime, type ComposedSshVerification } from "./puzedSshComposition.js";

interface Binding { bindingId: string; profileId: string; logicalHostIdentity: string; privateKeySecretId: string; revision: number; providerState?: JsonValue; operationId?: string; address?: { host: string; port: number; username: string; root: string }; }
interface State { schemaVersion: 1; revision: number; bindings: Record<string, Binding>; }

/** Host-owned durable composed-profile adapter. Private vault references never
 * cross the Puzed child; they are supplied only to the SSH provider callback. */
export class ExtensionHostComposedSshRuntime implements ComposedSshRuntime {
  private state: State | undefined; private writes = Promise.resolve();
  private readonly pendingProfiles = new Map<string, Binding>();
  constructor(private readonly file: string, private readonly hosts: Pick<ExtensionHostManager, "invokeProvider">) {}
  async getProfile(profileId: string, signal: AbortSignal): Promise<{ profileId: string; providerId: string; revision: number; values: JsonValue; secretFields: readonly string[] }> { signal.throwIfAborted(); const binding = this.pendingProfiles.get(profileId) ?? Object.values((await this.load()).bindings).find((item) => item.profileId === profileId); if (binding?.address === undefined) throw new Error("composed SSH profile is unavailable"); return { profileId, providerId: SSH_PROVIDER_ID, revision: binding.revision, values: { id: profileId, displayName: binding.logicalHostIdentity, hostname: binding.address.host, port: binding.address.port, username: binding.address.username, authMode: "private-key", privateKeySecretRef: binding.privateKeySecretId, defaultRoot: binding.address.root, logicalHostIdentity: binding.logicalHostIdentity, hostVerification: "strict" }, secretFields: [binding.privateKeySecretId] }; }
  async createBinding(input: Parameters<ComposedSshRuntime["createBinding"]>[0]): Promise<{ revision: number }> { return this.mutate(async (state) => { const prior = state.bindings[input.bindingId]; if (prior !== undefined) { if (prior.logicalHostIdentity !== input.logicalHostIdentity || prior.privateKeySecretId !== input.privateKeySecretId) throw new Error("composed SSH binding identity conflicts"); return { revision: prior.revision }; } state.bindings[input.bindingId] = { ...input, revision: 1 }; return { revision: 1 }; }); }
  async updateBinding(input: Parameters<ComposedSshRuntime["updateBinding"]>[0], signal: AbortSignal): Promise<{ revision: number }> {
    return this.mutate(async (state) => { const prior = required(state, input.bindingId); if (prior.revision !== input.expectedRevision) throw new Error("composed SSH binding revision changed"); if (prior.address !== undefined && sameAddress(prior.address, input) && prior.logicalHostIdentity === input.logicalHostIdentity) return { revision: prior.revision };
      const revision = prior.revision + 1; const pending = { ...prior, logicalHostIdentity: input.logicalHostIdentity, revision, address: { host: input.host, port: input.port, username: input.username, root: input.root } }; this.pendingProfiles.set(prior.profileId, pending); let result: ProvisioningResult; try { result = await this.hosts.invokeProvider({ providerId: SSH_PROVIDER_ID, callback: "createEnvironment", request: { environmentId: input.bindingId, displayName: input.logicalHostIdentity, profileId: prior.profileId, values: { id: prior.profileId, displayName: input.logicalHostIdentity, hostname: input.host, port: input.port, username: input.username, authMode: "private-key", privateKeySecretRef: prior.privateKeySecretId, defaultRoot: input.root, logicalHostIdentity: input.logicalHostIdentity, hostVerification: "strict" } }, idempotencyKey: `ssh-binding:${input.bindingId}:${revision}`, expectedRevision: prior.revision, signal }) as ProvisioningResult; } finally { this.pendingProfiles.delete(prior.profileId); }
      state.bindings[input.bindingId] = { ...prior, logicalHostIdentity: input.logicalHostIdentity, revision, address: { host: input.host, port: input.port, username: input.username, root: input.root }, providerState: result.providerState, ...(result.state === "pending" ? { operationId: result.operationId } : {}) }; return { revision }; });
  }
  async verifyBinding(input: Parameters<ComposedSshRuntime["verifyBinding"]>[0], signal: AbortSignal): Promise<ComposedSshVerification> { const state = await this.load(); const binding = required(state, input.bindingId); if (binding.revision !== input.expectedRevision || binding.providerState === undefined || binding.address === undefined) return { state: "unavailable", revision: binding.revision, code: "binding-not-ready", message: "SSH binding is not ready.", retryable: true };
    try { if (binding.operationId !== undefined) { const result = await this.hosts.invokeProvider({ providerId: SSH_PROVIDER_ID, callback: "resumeOperation", request: { environmentId: binding.bindingId, profileId: binding.profileId, providerState: binding.providerState, operationId: binding.operationId }, signal }) as ProvisioningResult; if (result.state === "pending") { await this.saveProviderState(binding.bindingId, result.providerState, result.operationId); return trustFromState(binding.revision, result.providerState, result.progress); } await this.saveProviderState(binding.bindingId, result.providerState); return { state: "ready", revision: binding.revision, canonicalRoot: result.status.defaultRoot ?? binding.address.root, logicalHostIdentity: binding.logicalHostIdentity }; }
      const status = await this.hosts.invokeProvider({ providerId: SSH_PROVIDER_ID, callback: "getStatus", request: { environmentId: binding.bindingId, profileId: binding.profileId, providerState: binding.providerState }, signal }) as { state: string; defaultRoot?: string; message?: string };
      return status.state === "available" ? { state: "ready", revision: binding.revision, canonicalRoot: status.defaultRoot ?? binding.address.root, logicalHostIdentity: binding.logicalHostIdentity } : { state: "unavailable", revision: binding.revision, code: "ssh-unavailable", message: status.message ?? "SSH is unavailable.", retryable: true };
    } catch { return { state: "unavailable", revision: binding.revision, code: "ssh-unavailable", message: "SSH is unavailable.", retryable: true }; }
  }
  async removeBinding(bindingId: string): Promise<void> { await this.mutate(async (state) => { delete state.bindings[bindingId]; }); }
  async approveTrust(input: Parameters<ComposedSshRuntime["approveTrust"]>[0], signal: AbortSignal): Promise<{ revision: number }> { const binding = required(await this.load(), input.bindingId); if (binding.revision !== input.expectedRevision || binding.providerState === undefined || binding.operationId === undefined) throw new Error("composed SSH trust revision changed"); const outcome = await this.hosts.invokeProvider({ providerId: SSH_PROVIDER_ID, callback: "invokeAction", request: { environmentId: binding.bindingId, profileId: binding.profileId, providerState: binding.providerState, actionId: input.action === "replace" ? "replace-host-key" : "trust-host", values: { challengeId: input.challengeId } }, expectedRevision: input.expectedRevision, signal }) as { providerState: JsonValue }; const resumed = await this.hosts.invokeProvider({ providerId: SSH_PROVIDER_ID, callback: "resumeOperation", request: { environmentId: binding.bindingId, profileId: binding.profileId, providerState: outcome.providerState, operationId: binding.operationId }, signal }) as ProvisioningResult; await this.saveProviderState(binding.bindingId, resumed.providerState, resumed.state === "pending" ? resumed.operationId : undefined); return { revision: binding.revision }; }
  private async saveProviderState(id: string, providerState: JsonValue, operationId?: string): Promise<void> { await this.mutate(async (state) => { const binding = required(state, id); state.bindings[id] = { ...binding, providerState, operationId }; }); }
  private async mutate<T>(work: (draft: State) => Promise<T>): Promise<T> { let output!: T; const next = this.writes.then(async () => { const before = await this.load(); const draft = structuredClone(before); output = await work(draft); draft.revision++; await mkdir(dirname(this.file), { recursive: true }); const temporary = `${this.file}.${randomUUID()}.tmp`; await writeFile(temporary, `${JSON.stringify(draft, null, 2)}\n`, { flag: "wx", mode: 0o600 }); await rename(temporary, this.file); this.state = draft; }); this.writes = next.catch(() => undefined); await next; return output; }
  private async load(): Promise<State> { if (this.state !== undefined) return this.state; try { const value = JSON.parse(await readFile(this.file, "utf8")) as State; if (value.schemaVersion !== 1 || !Number.isInteger(value.revision) || typeof value.bindings !== "object") throw new Error(); this.state = value; } catch (error) { if ((error as { code?: string }).code !== "ENOENT") throw new Error("composed SSH binding state is invalid"); this.state = { schemaVersion: 1, revision: 0, bindings: {} }; } return this.state; }
}
function required(state: State, id: string): Binding { const value = state.bindings[id]; if (value === undefined) throw new Error("composed SSH binding was not found"); return value; }
function sameAddress(left: Binding["address"], right: Parameters<ComposedSshRuntime["updateBinding"]>[0]): boolean { return left?.host === right.host && left.port === right.port && left.username === right.username && left.root === right.root; }
function trustFromState(revision: number, providerState: JsonValue, progress: { stages: Array<{ state: string; detail?: string }> }): ComposedSshVerification { const state = typeof providerState === "object" && providerState !== null && !Array.isArray(providerState) ? providerState : {}; const challenge = typeof state.trustChallenge === "object" && state.trustChallenge !== null && !Array.isArray(state.trustChallenge) ? state.trustChallenge : {}; const detail = progress.stages.find((stage) => stage.state === "active")?.detail ?? "unknown"; const [fallbackAlgorithm = "unknown", fallbackFingerprint = detail] = detail.split(" ", 2); return { state: "trust-required", revision, challengeId: typeof challenge.challengeId === "string" ? challenge.challengeId : `ssh-trust:${revision}`, algorithm: typeof challenge.algorithm === "string" ? challenge.algorithm : fallbackAlgorithm, fingerprint: typeof challenge.fingerprint === "string" ? challenge.fingerprint : fallbackFingerprint, changed: challenge.changed === true || challenge.reason === "host-key-mismatch" }; }
