import type { JsonValue } from '@terminay/protocol';
import type { QueryCommandTransport } from './queryCommand.js';
import type { CommandOptions, QueryOptions } from './types.js';

export const EXTENSION_OPERATIONS = Object.freeze({ list:'extensions.list', get:'extensions.get', previewInstall:'extensions.preview-install', install:'extensions.install', previewUpdate:'extensions.preview-update', enable:'extensions.enable', disable:'extensions.disable', restart:'extensions.restart', remove:'extensions.remove', update:'extensions.update', rollback:'extensions.rollback' } as const);
export type ExtensionAction = 'enable'|'disable'|'restart'|'remove'|'rollback';
export interface ExtensionClientSummary { readonly id:string; readonly packageName:string; readonly displayName:string; readonly description:string; readonly version?:string; readonly state:'available'|'installed'|'disabled'|'incompatible'|'failed'|'quarantined'|'pending'; readonly official:boolean; readonly permissions:readonly string[]; readonly dependants:readonly string[]; readonly provenance?:string; }
export interface ExtensionCatalogue { readonly authorityLabel:string; readonly revision:number; readonly extensions:readonly ExtensionClientSummary[]; }
export interface ExtensionInstallPreviewDto { readonly packageName:string; readonly version:string; readonly previewDigest:string; readonly integrity:string; readonly official:boolean; readonly permissions:readonly string[]; readonly providerIds:readonly string[]; readonly dependencies:readonly string[]; readonly audit:Readonly<{low:number;moderate:number;high:number;critical:number}>; readonly publisher?:string; readonly provenance?:string; readonly trustedCodeWarning?:string; }

export class ExtensionsClient {
	constructor(private readonly transport:QueryCommandTransport){}
	async list(options:QueryOptions={}):Promise<ExtensionCatalogue>{return parseCatalogue(await this.transport.query(EXTENSION_OPERATIONS.list,{},options));}
	async get(extensionId:string,options:QueryOptions={}):Promise<ExtensionClientSummary>{return parseSummary(await this.transport.query(EXTENSION_OPERATIONS.get,{extensionId:text(extensionId,256)},options));}
	async previewInstall(spec:string,options:QueryOptions={}):Promise<ExtensionInstallPreviewDto>{return parsePreview(await this.transport.query(EXTENSION_OPERATIONS.previewInstall,{spec:text(spec,512)},options));}
	async previewUpdate(extensionId:string,spec?:string,options:QueryOptions={}):Promise<ExtensionInstallPreviewDto>{return parsePreview(await this.transport.query(EXTENSION_OPERATIONS.previewUpdate,{extensionId:text(extensionId,256),...(spec===undefined?{}:{spec:text(spec,512)})},options));}
	async install(previewDigest:string,expectedRevision:number,options:CommandOptions={}):Promise<ExtensionCatalogue>{return parseCatalogue(await this.transport.command(EXTENSION_OPERATIONS.install,{previewDigest:text(previewDigest,256),expectedRevision:uintInput(expectedRevision),confirmation:true,idempotencyKey:operationKey(),deadlineAt:Date.now()+300_000},options));}
	async update(extensionId:string,previewDigest:string,expectedRevision:number,options:CommandOptions={}):Promise<ExtensionCatalogue>{return parseCatalogue(await this.transport.command(EXTENSION_OPERATIONS.update,{extensionId:text(extensionId,256),previewDigest:text(previewDigest,256),expectedRevision:uintInput(expectedRevision),confirmation:true,idempotencyKey:operationKey(),deadlineAt:Date.now()+300_000},options));}
	async action(action:ExtensionAction,extensionId:string,expectedRevision:number,options:CommandOptions={}):Promise<ExtensionCatalogue>{return parseCatalogue(await this.transport.command(EXTENSION_OPERATIONS[action],{extensionId:text(extensionId,256),expectedRevision:uintInput(expectedRevision),idempotencyKey:operationKey(),deadlineAt:Date.now()+300_000},options));}
}
function parseCatalogue(input:JsonValue):ExtensionCatalogue{const value=record(input);if(!uint(value.revision)||!Array.isArray(value.extensions)||value.extensions.length>512)throw new TypeError('extension catalogue is invalid');const installed=new Map(value.extensions.map(entry=>{const item=record(entry);return [text(item.extensionId,256),item] as const;}));const catalogue=Array.isArray(value.catalogue)?value.catalogue:[];if(catalogue.length>512)throw new TypeError('extension catalogue exceeds limit');const summaries=catalogue.map(entry=>parseSummary(entry,installed.get(text(record(entry).extensionId,256))));for(const [id,item] of installed){if(!summaries.some(summary=>summary.id===id))summaries.push(parseSummary(item,item));}return Object.freeze({authorityLabel:typeof value.authorityLabel==='string'?text(value.authorityLabel,256):'This server',revision:value.revision,extensions:Object.freeze(summaries)});}
function parseSummary(input:JsonValue,installed?:Record<string,JsonValue>):ExtensionClientSummary{const value=record(input);const runtime=installed?.runtimeState;const state:ExtensionClientSummary['state']=installed===undefined?'available':installed.compatible===false?'incompatible':installed.enabled===false?'disabled':runtime==='failed'?'failed':runtime==='quarantined'?'quarantined':installed.pendingVersion!==undefined?'pending':'installed';return Object.freeze({id:text(value.id??value.extensionId,256),packageName:text(value.packageName,256),displayName:typeof value.displayName==='string'?text(value.displayName,128):text(value.packageName,256),description:typeof value.description==='string'?text(value.description,1024,true):'',state,official:value.official===true,permissions:textArray(value.permissions,128),dependants:textArray(value.dependants,128),...(installed?.activeVersion===undefined?{}:{version:text(installed.activeVersion,128)}),...(value.provenance===undefined?{}:{provenance:text(value.provenance,512,true)})});}
function parsePreview(input:JsonValue):ExtensionInstallPreviewDto{const value=record(input);if(typeof value.official!=='boolean')throw new TypeError('extension preview is invalid');const auditValue=typeof value.audit==='object'&&value.audit!==null&&!Array.isArray(value.audit)?value.audit as Record<string,JsonValue>:{};const count=(key:string)=>uint(auditValue[key])?auditValue[key] as number:0;return Object.freeze({packageName:text(value.packageName,256),version:text(value.version??value.exactVersion,128),previewDigest:text(value.previewDigest,256),integrity:text(value.integrity??value.registryIntegrity,1024),official:value.official,permissions:textArray(value.permissions??value.declaredPermissions,128),providerIds:textArray(value.providerIds??value.declaredProviderIds,128),dependencies:textArray(value.dependencies,512),audit:Object.freeze({low:count('low'),moderate:count('moderate'),high:count('high'),critical:count('critical')}),...(value.publisher===undefined?{}:{publisher:text(value.publisher,256)}),...(value.provenance===undefined?{}:{provenance:text(value.provenance,128)}),...(value.trustedCodeWarning===undefined?{}:{trustedCodeWarning:text(value.trustedCodeWarning,2048,true)})});}
function textArray(value:unknown,max:number):readonly string[]{if(!Array.isArray(value)||value.length>max)return Object.freeze([]);return Object.freeze(value.map(item=>text(item,256)));}
function record(value:unknown):Record<string,JsonValue>{if(typeof value!=='object'||value===null||Array.isArray(value))throw new TypeError('expected object');return value as Record<string,JsonValue>;}
function text(value:unknown,max:number,empty=false):string{if(typeof value!=='string'||value.length>max||value.includes('\0')||(!empty&&value.length===0))throw new TypeError('invalid text');return value;}
function uint(value:unknown):value is number{return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0;}function uintInput(value:number):number{if(!uint(value))throw new TypeError('invalid revision');return value;}
function operationKey():string{return `ui-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;}
