import type {
  ByteTransport,
  ClientHello,
  CommandResultEnvelope,
  JsonValue,
  NegotiatedProtocol,
  ProtocolError,
  ProtocolId,
  ProtocolLimits,
  QueryResultEnvelope,
  ServerHello,
} from "@terminay/protocol";

/** Lifecycle states exposed by the application client (transport states are
 * intentionally kept as a separate protocol concern). */
export type ConnectionState =
  | "idle"
  | "connecting"
  | "connected"
  | "reconnecting"
  | "stale"
  | "closing"
  | "closed"
  | "failed";

export type ClientErrorCode =
  | ProtocolError["code"]
  | "disconnected"
  | "handshake_timeout"
  | "invalid_response"
  | "unknown_command_outcome"
  | "resync_required";

/** An error returned by the protocol, or one generated by the client itself. */
export class ClientError extends Error {
  readonly code: ClientErrorCode;
  readonly details?: JsonValue;
  readonly retryable: boolean;
  override readonly cause?: unknown;

  constructor(code: ClientErrorCode, message: string, options: {
    readonly details?: JsonValue;
    readonly retryable?: boolean;
    readonly cause?: unknown;
  } = {}) {
    super(message);
    this.name = "ClientError";
    this.code = code;
    if (options.details !== undefined) this.details = options.details;
    this.retryable = options.retryable === true;
    if (options.cause !== undefined) this.cause = options.cause;
  }
}

/** The transport went away after a command was sent. The mutation may have
 * committed on the server; callers must resolve it with commandStatus(). */
export class CommandOutcomeUnknownError extends ClientError {
  readonly commandId: ProtocolId;

  constructor(commandId: ProtocolId, cause?: unknown) {
    super("unknown_command_outcome", `command outcome is unknown: ${commandId}`, {
      retryable: true,
      ...(cause === undefined ? {} : { cause }),
    });
    this.name = "CommandOutcomeUnknownError";
    this.commandId = commandId;
  }
}

export class ClientDisconnectedError extends ClientError {
  constructor(message = "client is not connected", cause?: unknown) {
    super("disconnected", message, {
      retryable: true,
      ...(cause === undefined ? {} : { cause }),
    });
    this.name = "ClientDisconnectedError";
  }
}

export interface ConnectionSnapshot {
  readonly state: ConnectionState;
  readonly revision: number;
  readonly cursor: string;
  readonly stale: boolean;
  readonly reconnectAttempt: number;
  readonly server?: ServerHello;
  readonly negotiated?: NegotiatedProtocol;
  readonly error?: ClientError;
}

export interface ConnectionStateChange {
  readonly previous: ConnectionSnapshot;
  readonly current: ConnectionSnapshot;
  readonly reason?: ClientError | string;
}

export interface QueryOptions {
  /** A caller supplied id is useful when recovering an interrupted request. */
  readonly queryId?: ProtocolId;
  readonly deadlineMs?: number;
  readonly signal?: AbortSignal;
}

export interface CommandOptions {
  /** Stable across retries and reconnects. A generated id is stable for the
   * lifetime of the returned command promise. */
  readonly commandId?: ProtocolId;
  readonly expectedRevision?: number;
  readonly deadlineMs?: number;
  readonly signal?: AbortSignal;
}

export interface CommandStatusOptions {
  readonly signal?: AbortSignal;
  readonly deadlineMs?: number;
  /** Servers may expose a different operation name while migrating. */
  readonly operation?: string;
}

export interface ResyncOptions {
  readonly signal?: AbortSignal;
  readonly deadlineMs?: number;
  readonly operation?: string;
  readonly payload?: JsonValue;
}

export interface ResyncResult<T = JsonValue> {
  readonly revision: number;
  readonly cursor: string;
  readonly snapshot: T;
  readonly events?: readonly ClientEvent[];
}

export interface ClientEvent<T = JsonValue> {
  readonly subscriptionId: ProtocolId;
  readonly revision: number;
  readonly cursor: string;
  readonly event: string;
  readonly payload: T;
  readonly body?: Uint8Array;
}

export interface SubscriptionOptions {
  readonly subscriptionId?: ProtocolId;
  readonly fromRevision?: number;
  readonly cursor?: string;
  readonly signal?: AbortSignal;
  /** Operation used to create the server-side subscription. Set to false to
   * register a local listener only (handy for a pre-existing stream). */
  readonly operation?: string | false;
  readonly payload?: JsonValue;
}

export interface ClientSubscription<T = JsonValue> {
  readonly id: ProtocolId;
  readonly event?: string;
  readonly fromRevision: number;
  readonly unsubscribe: () => Promise<void>;
  readonly onEvent: (listener: (event: ClientEvent<T>) => void) => () => void;
  /** Bounded journal replay could not satisfy this subscription. Refresh the
   * feature snapshot, then create a new subscription from that cursor. */
  readonly onResync: (listener: (resync: ClientSubscriptionResync) => void) => () => void;
}

export interface ClientSubscriptionResync {
  readonly subscriptionId: ProtocolId;
  readonly revision: number;
  readonly cursor: string;
  readonly snapshot?: JsonValue;
}

export interface TerminayClientOptions {
  readonly transport: ByteTransport;
  readonly clientId?: ProtocolId;
  readonly clientVersion?: string;
  readonly capabilities?: readonly string[];
  readonly limits?: ProtocolLimits;
  readonly handshakeTimeoutMs?: number;
  readonly reconnect?: ReconnectOptions | false;
  readonly hostCapabilities?: HostCapabilitySet | HostCapabilityProvider;
}

export interface ReconnectOptions {
  readonly maxAttempts?: number;
  readonly initialDelayMs?: number;
  readonly maxDelayMs?: number;
  readonly factor?: number;
  readonly signal?: AbortSignal;
}

export type ClientQueryResult<T extends JsonValue = JsonValue> = QueryResultEnvelope & {
  readonly result?: T;
};

export interface ClientBinaryQueryResult<T extends JsonValue = JsonValue> {
  readonly envelope: ClientQueryResult<T>;
  readonly body: Uint8Array;
}

export type ClientCommandResult<T extends JsonValue = JsonValue> = CommandResultEnvelope & {
  readonly result?: T;
};

export interface PendingCommand {
  readonly commandId: ProtocolId;
  readonly correlationId: ProtocolId;
  readonly uncertain: boolean;
}

export interface HostCapabilitySet {
  readonly nativeWindows?: boolean;
  readonly secureStorage?: boolean;
  readonly notifications?: boolean;
  readonly filePicker?: boolean;
  readonly clipboard?: boolean;
  readonly serverExposure?: boolean;
  readonly connectionProfiles?: boolean;
  /** Desktop-owned presentation capabilities; never server settings. */
  readonly updater?: boolean;
  readonly osIntegration?: boolean;
}

export type HostCapability = keyof HostCapabilitySet;

export interface HostCapabilityProvider {
  readonly capabilities: HostCapabilitySet;
  has(capability: HostCapability): boolean;
  require(capability: HostCapability): void;
}

/** Optional host operations are capability-gated and transport-neutral. They
 * deliberately contain no Electron, Node, WebRTC, or filesystem types. */
export interface HostActions {
  readonly openWindow?: (request: { readonly view?: string; readonly serverId?: ProtocolId }) => Promise<void>;
  readonly chooseFile?: (request?: { readonly multiple?: boolean }) => Promise<readonly string[]>;
  readonly writeClipboard?: (text: string) => Promise<void>;
  readonly readClipboard?: () => Promise<string>;
  readonly showNotification?: (request: { readonly title: string; readonly body?: string }) => Promise<void>;
}

export interface TerminayHost {
  readonly capabilities: HostCapabilityProvider;
  readonly actions?: HostActions;
}

export function toClientError(error: ProtocolError | ClientError | unknown): ClientError {
  if (error instanceof ClientError) return error;
  if (isProtocolError(error)) {
    return new ClientError(error.code, error.message, {
      ...(error.details === undefined ? {} : { details: error.details }),
      ...(error.retryable === undefined ? {} : { retryable: error.retryable }),
    });
  }
  if (error instanceof Error) return new ClientError("internal", error.message, { cause: error });
  return new ClientError("internal", String(error));
}

function isProtocolError(value: unknown): value is ProtocolError {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return typeof candidate.code === "string" && typeof candidate.message === "string";
}

export type ClientTransport = ByteTransport;
export type ClientHelloEnvelope = ClientHello;
