import type { ExtensionAction, ExtensionInstallPreviewDto } from '@terminay/client-core';
import { useMemo, useState } from 'react';
import type { ExtensionSummaryDto } from './uiModel';

export function ExtensionManager({ extensions, serverName, onPreview, onInstall, onAction }: Readonly<{
	extensions: readonly ExtensionSummaryDto[];
	serverName: string;
	revision: number;
	onPreview: (spec:string) => Promise<ExtensionInstallPreviewDto>;
	onInstall: (digest:string) => Promise<void>;
	onAction: (action:ExtensionAction,id:string) => Promise<void>;
}>) {
	const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState(extensions[0]?.id??''); const [npmPackage,setNpmPackage]=useState(''); const [preview,setPreview]=useState<ExtensionInstallPreviewDto|null>(null); const [previewError,setPreviewError]=useState(''); const [busy,setBusy]=useState(false);
	const filtered=useMemo(()=>extensions.filter(item=>`${item.displayName} ${item.packageName} ${item.description}`.toLowerCase().includes(query.trim().toLowerCase())),[extensions,query]); const selected=extensions.find(item=>item.id===selectedId)??filtered[0];
	const previewPackage=async()=>{setBusy(true);setPreviewError('');try{setPreview(await onPreview(npmPackage));}catch(error){setPreviewError(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
	const act=async(action:ExtensionAction,id:string)=>{setBusy(true);try{await onAction(action,id);}finally{setBusy(false);}};
	return <div className="environment-manager extension-manager" aria-busy={busy}>
		<header className="management-route-header"><div><p className="management-route-eyebrow">Selected Terminay Server</p><h2>Extensions</h2><p>Extensions run as trusted code on <strong>{serverName}</strong>.</p></div></header>
		<div className="trusted-code-warning" role="note"><strong>Third-party extensions are trusted code.</strong><span>They can access files and networks available to the selected server account.</span></div>
		<form className="extension-install" onSubmit={event=>{event.preventDefault();void previewPackage();}}><label><span>Install from npm</span><input value={npmPackage} onChange={event=>setNpmPackage(event.target.value)} placeholder="package-name or package-name@version" /></label><button type="submit" disabled={busy||npmPackage.trim()===''}>Preview</button></form>
		{previewError?<p role="alert">{previewError}</p>:null}
		{preview?<section className="extension-preview" aria-label="Extension installation preview"><h3>Confirm {preview.packageName}@{preview.version}</h3><dl><div><dt>Integrity</dt><dd>{preview.integrity}</dd></div><div><dt>Publisher</dt><dd>{preview.publisher??'Not provided'}</dd></div><div><dt>Provenance</dt><dd>{preview.provenance??'Unavailable'}</dd></div></dl><h4>Permissions</h4><ul>{preview.permissions.map(permission=><li key={permission}>{permission}</li>)}</ul>{preview.trustedCodeWarning?<p className="trusted-code-warning">{preview.trustedCodeWarning}</p>:null}<div className="management-route-actions"><button type="button" onClick={()=>setPreview(null)}>Cancel</button><button type="button" onClick={()=>void onInstall(preview.previewDigest)}>Install on {serverName}</button></div></section>:null}
		<div className="management-route-grid"><aside className="management-route-list" aria-label="Extensions"><label><span className="sr-only">Search extensions</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search extensions" /></label>{filtered.map(item=><button type="button" key={item.id} className={item.id===selected?.id?'is-selected':''} onClick={()=>setSelectedId(item.id)}><span><strong>{item.displayName} {item.official?<em>Official</em>:null}</strong><small>{item.packageName}</small></span><span>{item.state}</span></button>)}</aside>
		<section className="management-route-detail" aria-live="polite">{selected?<><div className="management-route-title"><span className="management-route-icon" aria-hidden="true">⌘</span><div><h3>{selected.displayName}</h3><p>{selected.description}</p></div></div><dl><div><dt>Package</dt><dd>{selected.packageName}</dd></div><div><dt>Version</dt><dd>{selected.version??'Not installed'}</dd></div><div><dt>Source</dt><dd>{selected.provenance??'npmjs.com'}</dd></div><div><dt>State</dt><dd>{selected.state}</dd></div></dl><h4>Permissions</h4><ul>{selected.permissions.map(permission=><li key={permission}>{permission}</li>)}</ul>{selected.dependants.length>0?<p className="management-route-note"><strong>Required by:</strong> {selected.dependants.join(', ')}</p>:null}<div className="management-route-actions">{selected.state==='available'?<button type="button" onClick={()=>{setNpmPackage(selected.packageName);void onPreview(selected.packageName).then(setPreview);}}>Install</button>:<button type="button" onClick={()=>void act(selected.state==='disabled'?'enable':'disable',selected.id)}>{selected.state==='disabled'?'Enable':'Disable'}</button>}<button type="button" disabled={selected.version===undefined} onClick={()=>void act('restart',selected.id)}>Restart</button><button type="button" disabled={selected.version===undefined} onClick={()=>void act('rollback',selected.id)}>Rollback</button><button type="button" className="danger" disabled={selected.dependants.length>0||selected.version===undefined} onClick={()=>void act('remove',selected.id)}>Uninstall</button></div></>:<p>Select an extension.</p>}</section></div>
	</div>;
}
