import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const gateway = await readFile('src/services/fileViewer/terminayFileGateway.ts', 'utf8')
const compatibility = await readFile('src/services/fileViewer/legacyFileViewerTransport.ts', 'utf8')
const performantTextViewer = await readFile('src/components/file-viewer/modes/PerformantTextViewer.tsx', 'utf8')
const filePanel = await readFile('src/components/file-viewer/FilePanel.tsx', 'utf8')
const settingsHook = await readFile('src/hooks/useTerminalSettings.ts', 'utf8')
const recordingsWindow = await readFile('src/components/RecordingsWindow.tsx', 'utf8')
const recordingsCompatibility = await readFile('src/services/recordings/legacyRecordingsClient.ts', 'utf8')
const app = await readFile('src/App.tsx', 'utf8')
const recordingController = await readFile('src/workspace/useTerminalRecordingController.ts', 'utf8')

test('file diff UI path uses the shared client facade with an injected narrow compatibility capability', () => {
  assert.match(gateway, /FileViewerClient/)
  assert.match(gateway, /fileViewerClient\.getGitDiff/)
  assert.doesNotMatch(gateway, /window\.terminay\.getGitDiff/)
  assert.match(compatibility, /createLegacyFileViewerTransport\(api: LegacyFileViewerApi\)/)
  assert.match(compatibility, /api\.getGitDiff\(path\)/)
  assert.doesNotMatch(compatibility, /window\.terminay/)
  assert.match(compatibility, /Compatibility-only adapter/)
})

test('performant text viewer uses shared ranged text queries, with preload isolated to compatibility adapter', () => {
  assert.match(performantTextViewer, /fileViewerClient: FileViewerClient/)
  assert.match(performantTextViewer, /\.getTextMetadata\(/)
  assert.match(performantTextViewer, /\.readTextLines\(/)
  assert.doesNotMatch(performantTextViewer, /window\.terminay\.getFileTextMetadata/)
  assert.doesNotMatch(performantTextViewer, /window\.terminay\.readFileTextLines/)
  assert.match(compatibility, /file\.text-metadata/)
  assert.match(compatibility, /file\.text-lines/)
  assert.match(compatibility, /api\.getFileTextMetadata/)
  assert.match(compatibility, /api\.readFileTextLines/)
  assert.doesNotMatch(compatibility, /window\.terminay/)
})

test('terminal settings hook uses the selected server SettingsClient', () => {
  assert.match(settingsHook, /useContext\(TerminalSettingsClientContext\)/)
  assert.doesNotMatch(settingsHook, /createLegacySettingsClient|getLegacySettingsCapability/)
  assert.match(settingsHook, /settingsClient\.(get|onChanged)/)
  assert.doesNotMatch(settingsHook, /window\.terminay\.getTerminalSettings/)
  assert.doesNotMatch(settingsHook, /window\.terminay\.onTerminalSettingsChanged/)
})

test('file panel uses shared file/settings clients, with preload isolated to adapters', () => {
  assert.match(filePanel, /disconnectedFilePanelCompatibility\.createClient\(\)/)
  assert.match(filePanel, /\.getTextMetadata\(/)
  assert.match(filePanel, /\.readTextLines\(/)
  assert.match(filePanel, /\.saveSparseFile\(/)
  assert.match(filePanel, /useTerminalSettings\(\)/)
  assert.match(filePanel, /settingsClient\.update\(/)
  assert.doesNotMatch(filePanel, /window\.terminay\./)
  assert.match(compatibility, /file\.save-sparse/)
})

test('recordings timeline uses the shared client facade, with preload isolated to compatibility adapter', () => {
  assert.match(recordingsWindow, /createLegacyRecordingsClient/)
  assert.match(recordingsWindow, /recordingsClient\.(list|replay|delete|reveal)/)
  assert.doesNotMatch(recordingsWindow, /window\.terminay\.listTerminalRecordings/)
  assert.doesNotMatch(recordingsWindow, /window\.terminay\.readTerminalRecordingChunk/)
  assert.doesNotMatch(recordingsWindow, /window\.terminay\.deleteTerminalRecordingById/)
  assert.doesNotMatch(recordingsWindow, /window\.terminay\.revealTerminalRecordingById/)
  assert.match(recordingsCompatibility, /new TerminayClientFacade/)
  assert.match(recordingsCompatibility, /recordings\.(list|replay|delete|reveal)/)
  assert.match(recordingsCompatibility, /captureLegacyRecordingsCapability\(api\)/)
  assert.doesNotMatch(recordingsCompatibility, /window\.terminay/)
})

test('App recording lifecycle injects server and narrow compatibility clients into its feature controller', () => {
  assert.match(app, /createLegacyRecordingsClient\(\s*window\.terminayRecordingServiceHost,?\s*\)/)
  assert.match(app, /useTerminalRecordingController\(\{/)
  assert.match(recordingController, /\(serverClient \?\? legacyClient\)\.start/)
  assert.match(recordingController, /\(serverClient \?\? legacyClient\)\.stop/)
  assert.match(recordingController, /legacyClient\.(getState|reveal)/)
  assert.match(recordingController, /legacyClient\.onStateChanged/)
  assert.doesNotMatch(app, /window\.terminay\.startTerminalRecording/)
  assert.doesNotMatch(app, /window\.terminay\.stopTerminalRecording/)
  assert.doesNotMatch(app, /window\.terminay\.getTerminalRecordingState/)
  assert.doesNotMatch(app, /window\.terminay\.revealTerminalRecordingById/)
  assert.doesNotMatch(app, /window\.terminay\.onTerminalRecordingChanged/)
  assert.match(recordingsCompatibility, /new RecordingsClient/)
  assert.match(recordingsCompatibility, /getTerminalRecordingState/)
  assert.match(recordingsCompatibility, /onTerminalRecordingChanged/)
})
